include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart

linter:
  rules:
    avoid_renaming_method_parameters: false
    library_prefixes: false
