name: "{{name}}"
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  enum_utils: ^0.3.0
  flutter:
    sdk: flutter
  flutter_jimtl: ^0.0.3
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.18.0
  fpdt: ^0.0.35
  freezed_annotation: ^2.1.0
  functional_widget_annotation: ^0.10.0
  hooks_riverpod: ^1.0.0
  intl: ^0.17.0
  logging: ^1.0.1
  navigation_stack: ^0.1.0
  url_launcher: ^6.0.6

dev_dependencies:
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0
  functional_widget: ^0.10.0
  jimtl_codegen: ^0.0.3
  json_serializable: ^6.0.0
  test: any

flutter:
  uses-material-design: true

  assets:
    - assets/arb/
    - assets/images/

flutter_icons:
  ios: true
  image_path: "assets/icon/icon.png"
  android: "launcher_icon"
  adaptive_icon_background: "assets/icon/icon_bg.png"
  adaptive_icon_foreground: "assets/icon/icon_fg.png"
